# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('idlancamento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamento.Categoria')),
            ],
        ),
    ]
